# -*- python -*-

env = Environment()
env["CPPFLAGS"] = "-O2 -Wall -std=c++11 -fprofile-arcs -ftest-coverage -g"
env["GCC"] = "/usr/bin/gcc"

SConscript(["SConscript", "tst/SConscript"], exports = "env")
#SConscript(["SConscript"], exports = "env")
