# -*- python -*-

env = Environment()
env["CPPFLAGS"] = "-O2 -Wall -fprofile-arcs -ftest-coverage -g"
env["GCC"] = "/usr/bin/g++"

SConscript(["SConscript", "tst/SConscript"], exports = "env")
#SConscript(["SConscript"], exports = "env")
