# -*- python -*-

import os

Import("env")
env = env.Clone()

sources = [
    "Bencoder.cpp"
    ]

# Compile
libbencoder = env.SharedLibrary(
                "bencoder",
                CPPPATH = ["../include/"],
                LIBS = ['gcov'],
                source  = ["src/%s" % x for x in sources],
              )

Default(libbencoder)
